services:
  postgres:
    image: postgres:15
    container_name: student-postgres
    environment:
      POSTGRES_USER: student
      POSTGRES_PASSWORD: student
      POSTGRES_DB: medscan
    ports:
      - "5433:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: student-cloudbeaver
    ports:
      - "8978:8978"
    depends_on:
      - postgres
    volumes:
      - ./data/cloudbeaver:/opt/cloudbeaver/workspace

  python:
    build: ./python
    container_name: student-python
    volumes:
      - .:/workspace
    stdin_open: true
    tty: true
    depends_on:
      - postgres
